---
title: "Mapping Exercise"
author: "Becca Portman"
date: "2/21/2017"
output: html_document
---
```{r}
library(WDI)
library(dplyr)
library(ggmap)
library(maptools)
library(maps)
```

```{r}
WDIsearch('health expenditure')
```

```{r}
df <- WDI(indicator = "SH.XPD.TOTL.ZS" ,
         start = 2014, end = 2014, extra = F)
df <- df %>% filter(!is.na(SH.XPD.TOTL.ZS))
df <- dplyr::rename(df, code = iso2c, expgdp = SH.XPD.TOTL.ZS)
df <- df %>% mutate(expgdp = as.numeric(expgdp))
```

World map of health expenditures as a share of GDP
```{r}
us.states <- map_data("state")
world <- map_data("world")
ggplot() + geom_polygon( data = world, aes(x=long,y=lat,group=group), 
                         color = "grey", fill = NA)

```
```{r}
library(dplyr)
library(tidyverse)
library(stringr)
library(countrycode)
world <- as_data_frame(world)
world <- dplyr::rename(world, country=region)
world$subregion = NULL
world$country <- str_to_title(world$country)
world <- mutate(world, code = countrycode(world$country, "country.name", "iso2c"))
world.merged <-  left_join(world, df, by = "code")

```
```{r}
(gdpmap <- ggplot(world.merged, 
                        aes(x = long, y = lat, group=group)) + 
  geom_polygon(aes(fill = expgdp), color="white") 
  + theme_minimal())
```

```{r}
library(countrycode)
world.merged <- mutate(world.merged, region = countrycode(world.merged$code, "iso2c", "region"))
```
```{r}
(gdpmap <- ggplot(world.merged, 
                        aes(x = long, y = lat, group=group)) + 
  geom_polygon(aes(fill = expgdp), color="white") +
  facet_wrap(~region) + theme_minimal())

```
```{r}
library(readr)
setwd("/Users/rebeccaportman/Desktop/Spring 2017/Data Viz/dataviz-forum/exercise_maps/exercise")
fortune500 <- read_csv("fortune500.csv")
```
```{r}
by_state <- group_by(fortune500, state) %>% 
  summarise(n = n())
by_state
```
```{r}
library(stringr)
us.states <- as_data_frame(us.states)
us.states <- dplyr::rename(us.states, state=region)
us.states$subregion = NULL
us.states$state <- str_to_title(us.states$state)
# Add State Abbreviations and Centers
statenames <- as_data_frame(cbind(state=state.name, 
                state.abb = state.abb, state.center.x = state.center$x, 
                state.center.y = state.center$y))
statenames <- statenames %>% mutate_each_(funs(as.numeric), 
                vars=c("state.center.x","state.center.y"))
us.states <- left_join(us.states,statenames)
f500.merged = left_join(us.states, by_state)
f500.merged <- mutate(f500.merged, n = as.numeric(n))
f500.merged["n"][is.na(f500.merged["n"])] <- 0

```
```{r}
(f500map <- ggplot(f500.merged, 
                        aes(x = long, y = lat, group=group)) +  geom_polygon(aes(fill = n), color="white"))
```

```{r}
library(readxl)
setwd("/Users/rebeccaportman/Desktop/Spring 2017/Data Viz/dataviz-forum/exercise_maps/exercise")
corpinctax<- read_excel("State_Corporate_Income_Tax_Rates_2015.xlsx", sheet = 2, col_names = TRUE)
corpinctax <- mutate(corpinctax, topcorpinctax = as.numeric(topcorpinctax))
corpinctax$state <- str_trim(corpinctax$state)
corpinctax$state <- str_to_title(corpinctax$state)
corpinctax <- merge(corpinctax, statenames, by = "state")
corptax.merged <- left_join(us.states, corpinctax)
(corptaxmap <- ggplot(corptax.merged, 
                        aes(x = long, y = lat, group=group)) +  geom_polygon(aes(fill = topcorpinctax), color="white"))
```

```{r}
f500.merged = left_join(f500.merged, corptax.merged)
ggplot(f500.merged) + geom_point(aes(x=topcorpinctax, y = n)) + theme_minimal() + geom_smooth(aes(x=topcorpinctax, y = n), formula = y ~ x, color = "red")
```

```{r}
library(readr)
setwd("/Users/rebeccaportman/Desktop/Spring 2017/Data Viz/dataviz-forum/exercise_maps/exercise")
population <- read_csv("population.csv")
f500.merged <- left_join(f500.merged, population)
f500.merged$hqspercapita <- (f500.merged$n/f500.merged$julypop)
ggplot(f500.merged) + geom_point(aes(x=topcorpinctax, y = hqspercapita)) + theme_minimal() + geom_smooth(aes(x=topcorpinctax, y = hqspercapita), formula = y ~ x, color = "red")
```

```{r}
library(ggmap)
geocode("702 S.W. Eighth St. Bentonville Arkansas 72716", output = "latlon" , source = "google")
fortune500$address <- paste(fortune500$streetadd, fortune500$place, fortune500$state, fortune500$zip)
geocodes <- geocode(fortune500$address, output = "latlon" , source = "google")
```
```{r}
fortune500$lon <- geocodes$lon
fortune500$lat <- geocodes$lat
(corptaxmap <- ggplot() +  geom_polygon(data = corptax.merged, aes(x = long, y = lat, group = group, fill = topcorpinctax), color="white") + geom_point(aes(x= lon, y = lat), data = fortune500, size=2, alpha=0.3, color="red")) 
```

